### ISSUE TITLE
Missing chunks

### ISSUE THREAD

**Issue by aktiWeb** [prewk/XmlStreamer#14]
At first many thanks! Your tool helps me to read and import 2500 nodes from a 14MB file with very small memory consumption.

But after first tests, i get 30% only...
After checking your code i solved the problem by putting $this->chunkCompleted(); from line 236 one line up, inside the while(true) opened in line 155.

Please check and verify this issue.

Best regards
Dietmar

**Comment by prewk** [comment]
I'm glad it has helped you! However, this package is deprecated and no longer maintained/updated. You should check out [xml-string-streamer](https://github.com/prewk/xml-string-streamer) instead. It's been a long while since I made this and making the change you propose would be too dangerous for the legacy users.

But thanks for contributing!

14 MB is pretty small, if I were you I'd just load it into memory and don't bother with streaming. But I guess you have special requirements? :)
